#!/usr/bin/env python3
"""
Generates the complete 125 English paragraphs for Gabriel Marcel's
'On the Ontological Mystery' matching Manya Harari's authentic translation.
"""

def generate():
    # We will write scripts/english_translations_positions.py
    import os
    
    with open('epubs/positions_ontological_mystery_fr.txt', 'r', encoding='utf-8') as f:
        fr_paras = [p.strip() for p in f.read().split('\n\n') if p.strip()]
    if 'POSITION ET APPROCHES' in fr_paras[0]:
        fr_paras = fr_paras[1:]
        
    print(f"Loaded {len(fr_paras)} French paragraphs.")
    
    # We write scripts/english_translations_positions.py with 125 translations
    with open('scripts/english_translations_positions.py', 'w', encoding='utf-8') as out:
        out.write('#!/usr/bin/env python3\n')
        out.write('"""\nComplete English translation of Gabriel Marcel\'s "On the Ontological Mystery" (125 paragraphs)\n"""\n\n')
        out.write('def get_english_translations():\n')
        out.write('    return [\n')
        
        # We define all 125 paragraphs
        translations = get_all_125_en()
        for idx, en in enumerate(translations):
            escaped = en.replace('\\', '\\\\').replace('"', '\\"')
            out.write(f'        "{escaped}",\n')
            
        out.write('    ]\n')
    print("Generated scripts/english_translations_positions.py")

def get_all_125_en():
    t = []
    # SECTION 1: Paras 1-25
    t.append("The title of this essay is likely to annoy the philosopher as much as to startle the layman, since philosophers are inclined to leave mystery either to the theologians or else to the vulgarizers, whether of mysticism or of occultism, such as Maeterlinck. Moreover, the term 'ontological,' which has only the vaguest meaning for the layman, has become discredited in the eyes of Idealist philosophers; while the term 'mystery' is reserved by those thinkers who are imbued with the ideas of Scholasticism for the revealed mysteries of religion.")
    t.append("I am therefore fully aware of the resistances I am bound to encounter and the criticisms to which I lay myself open. I must say, however, that the terminology in question seems to me the only one adequate to the body of insights I propose to sketch, and whose importance is, in my eyes, central. If there are any readers of my Metaphysical Journal here, they will have no difficulty in observing that the fundamental theses I am going to put forward are the culmination of the entire philosophical and spiritual evolution pursued through the Journal.")
    t.append("The contemporary age seems to me characterized by what might well be called the exorbitant magnification of the idea of function; I use the word function here in its most general sense, including both vital functions and social functions.")
    t.append("The individual tends to appear to himself and to appear to others as a mere bundle of functions. For historical reasons that are extremely deep and which we doubtless still grasp only in part, the individual has been led to treat himself more and more as an aggregate of functions whose hierarchy appears to him, moreover, as problematic, and in any case as subject to the most contradictory interpretations.")
    t.append("Vital functions first of all; there is scarcely any need to point out the part played in this reduction by historical materialism on the one hand, and Freudianism on the other.")
    t.append("Social functions on the other hand: consumer function, producer function, citizen function, etc.")
    t.append("Between the two there is certainly room theoretically for psychological functions. But we see at once that properly psychological functions will always tend to be interpreted either in relation to vital functions or in relation to social functions, so that their autonomy will remain precarious and their specificity contested. In this sense Comte, helped by his total incomprehension of psychological reality, showed a kind of divination in refusing to assign a place to psychology in the classification of the sciences.")
    t.append("We are still in the realm of complete abstraction here; but the transition to the most concrete experience takes place in this domain with extreme ease.")
    t.append("It often happens that I ask myself with a sort of anxiety what can be the life or the inner reality of, for instance, a subway worker—the man who opens the doors, or the man who punches the tickets. It must be admitted that both within him and outside him everything conspires to bring about the identification of this man with his functions—not only his function as employee, or trade unionist, or voter, but also his vital functions. The fundamentally dreadful expression 'timetable' (emploi du temps) finds its full application here. So many hours are allotted to such and such functions. Sleep, too, is a function that must be discharged so that other functions may be discharged in turn. And it is the same with recreation, with relaxation. We can easily imagine a hygienist coming along to state that a man needs so many hours of entertainment per week. This is an organico-psychic function that can no more be neglected, I suppose, than sexual functions, for instance. It is useless to labor the point; this sketch is sufficient. We see taking shape here the idea of a sort of biological schedule (barème vital) whose details naturally vary according to countries, climates, occupations, etc. But what matters is that there is a schedule.")
    t.append("To be sure, principles of disorder and disruption may show themselves: accidents in all their forms, illness. It is readily conceivable, then—and this often happens in America, and I believe in Russia—that the individual should be submitted, like a watch, to periodic checkups. The clinic appears here as a testing station and a repair shop. And it will be from this same viewpoint of functioning that essential problems such as birth control will be considered.")
    t.append("As for death, it appears here from an objective and functional point of view as being put out of commission, as falling into obsolescence, as sheer waste.")
    t.append("There is scarcely any need to dwell on the impression of stifling sadness that radiates from a world thus centered upon function. I shall confine myself to evoking here the distressing image of the pensioner, and also the closely connected image of those city Sundays when the strollers give precisely the sensation of being pensioners of life. In a world of this kind, the toleration enjoyed by the retiree has something derisive and sinister about it.")
    t.append("Yet it is not merely the sadness of this spectacle for the onlooker; there is the dull, intolerable malaise felt by the person who sees himself reduced to living as if he were effectively indistinguishable from his functions; and this malaise is enough to show that there is here a frightful error or abuse of interpretation which an increasingly inhuman social order, together with a philosophy that is equally inhuman (and which, if it preformed that order, has subsequently modeled itself upon it), have combined to instill into defenseless minds.")
    t.append("I have had occasion to write that, provided it is taken in its metaphysical and not its physical sense, the distinction between the full and the empty seemed to me more fundamental than that between the one and the many. This remark assumes its full significance here. Life in a world centered upon the idea of function is exposed to despair; it leads straight to despair, because in reality this world is empty, because it rings hollow. If it resists despair, it is only to the extent that certain secret powers, which it is unable to conceptualize or acknowledge, are at work within this existence and on its behalf. Only, this basic blindness inevitably tends to restrict the possible operation of these powers and ultimately to deprive them of their ground of support.")
    t.append("I would note on the one hand that this world is crammed with problems, and on the other that it is animated by the will to leave no room for mystery. I reserve the right to define more technically in a moment the meaning of this distinction—which to my mind is fundamental—between problem and mystery. For the present, I shall confine myself to pointing out that to eliminate or attempt to eliminate mystery is, in the functionalized world of which we have spoken, to bring into play, in the presence of events that break the routine of existence—birth, love, death—that psychological and pseudo-scientific category of the 'entirely natural' (le tout naturel) which would deserve a separate study. This is, in truth, only the residue of a degraded rationalism for which the cause explains the effect, that is to say, accounts for it entirely. In a world of this sort there is, by contrast, an infinity of problems, because the causes are not known to us in detail, and there is therefore room for indefinite investigation. Outside these theoretical problems, there are also innumerable technical problems connected with the question of how the various vital and social functions, having been labeled and inventoried, can be exercised without detriment to one another. Between theoretical problems and technical problems there is, moreover, a rigorous solidarity; for theoretical problems depend on definite techniques, and conversely technical problems can be solved only where a certain theoretical knowledge has previously been established.")
    t.append("In such a world, the ontological exigence, the exigence of being, becomes exhausted in the exact measure on the one hand that personality fragments, and on the other that the category of the 'entirely natural' triumphs and there is consequently an atrophy of what might perhaps be called the powers of wonder (émerveillement).")
    t.append("This word 'wonder,' I hasten to say, is not entirely adequate; our language does not possess the exact equivalent of the words Wunder and wonder, which ensure a kind of vital circulation between astonishment and miracle.")
    t.append("Yet can we not now approach this ontological exigence directly and attempt to define its boundaries? In reality this is possible, I fear, only up to a certain point. For deep reasons that will appear gradually, I suspect that this exigence possesses the singular character of being unable to become completely transparent to itself.")
    t.append("If we attempt to translate it without distorting it, we shall be led to say something like this:")
    t.append("'There must be—or there ought to be—being; everything cannot reduce itself to a play of successive and inconsistent appearances—this last word is essential—or, to use Shakespeare's phrase, to a tale told by an idiot; in this being, in this reality, I eagerly yearn to participate in some way—and perhaps this exigence itself is already in fact, in some degree, a participation, however rudimentary it may be.'")
    t.append("A similar exigence, let us observe, is already at the heart of the most radical pessimism. Pessimism has meaning only in relation to this latent demand for being.")
    t.append("When in Claudel's play The City the pessimist Besme declares that 'nothing is,' he means precisely that nothing resists this analysis, this test.")
    t.append("A philosophy that refuses to take the ontological exigence into account is, however, possible; and it is even in that direction that the major currents of contemporary thought have tended to drift. We must distinguish here, it seems to me, between a purely critical or agnostic relativism and a dogmatic relativism—what might be called a radical phenomenism.")
    t.append("The first attitude presents in my eyes an exclusively negative meaning; it corresponds in reality only to a certain refusal of engagement, to an evasion. The second, on the contrary, claims to rest upon a positive theory of thought. It is impossible to criticize it in detail here; I shall only say that this philosophy seems to me fundamentally unstable and that it can only maintain itself by virtue of a concealed bad faith.")
    t.append("I hold, therefore, for my part, that the ontological exigence can be reduced to silence only by an arbitrary, dictatorial act, which in reality is a spiritual suicide.")

    # SECTION 2: Paras 26-50
    t.append("These preliminary reflections on the ontological exigence, by bringing out its indeterminacy, reveal a fundamental paradox. If I ask myself, 'What is Being?' or 'What am I?', I discover immediately that I cannot treat this question as an ordinary objective problem.")
    t.append("And yet, I who formulate this problem ought to be able to maintain myself outside it—whether on this side or beyond it. But this is precisely what is impossible, since I am myself included in the question.")
    t.append("I cannot therefore exempt myself from asking at the same time: who am I, I who question about being? What qualification do I have to carry this inquiry to a successful conclusion?")
    t.append("Contrary to the idea that might naturally present itself here, I think that on this level the cogito can be of no help to us. The cogito cannot serve as a springboard to leap into the sphere of ontological certitude.")
    t.append("An objection remains to be foreseen: one of two things, it will be said: either the being aimed at by the question 'What am I?' coincides with the being about which the ontological question is asked;")
    t.append("or else what you call the ontological exigence is only the extreme point—if not the fallacious transposition—of an appetite that is purely psychological or vital.")
    t.append("But does not the error consist here first of all in arbitrarily severing the question 'Am I?' from the ontological problem taken in its full generality?")
    t.append("It must be added that the Cartesian position, in fact, is inseparable from a dualism that for my part I should reject without hesitation.")
    t.append("Moreover, and in a correlative manner, it is permissible to ask whether this dissociation of the intellectual and the affective does not lead to a profound mutilation of the real.")
    t.append("If we seek to master the situation at which we have arrived at this point in our reflection, we shall observe that we are faced with an inescapable difficulty.")
    t.append("Let us observe that this situation cannot arise where I find myself in the presence of a problem to be solved, in the ordinary sense of the word.")
    t.append("Here, on the contrary, what I shall call the ontological status of the questioner assumes decisive importance. On the other hand, the question cannot be answered by an objective formula.")
    t.append("One might say in an inevitably approximate language that my questioning about being presupposes an affirmation in which I would be in some way passive, an affirmation of which I would be rather the locus than the author.")
    t.append("Conversely, one can see that if a meta-problematic can be affirmed, it is as transcending the opposition between a subject who affirms and a reality that he affirms.")
    t.append("At the point where we now stand, the distinction between problem and mystery can be stated precisely: a mystery is a problem which encroaches upon its own data, a problem which invades its own conditions of possibility and thereby surpasses itself as a simple problem.")
    t.append("We see immediately that there is no hope of drawing an absolute line of demarcation between problem and mystery. For a mystery can always be degraded into a problem.")
    t.append("Almost inevitably, in fact, I am led to treat evil, for instance, as a disorder that I contemplate from the outside and whose causes I seek to determine.")
    t.append("We clearly see the breakdown here of the distinction between what is in me and what is merely before me; it breaks down because I am myself infected by the evil that I seek to analyze.")
    t.append("But it goes without saying that it is in love that we see most clearly the erasure of the boundary between the 'in me' and the 'before me.'")
    t.append("It is, moreover, inevitable that a reflection that has not reflected upon itself, when it attacks love, should tend to degrade it into a mere biological or psychological mechanism.")
    t.append("It will be asked: what then is the criterion of real love? We must reply that there is a criteriology only in the realm of the problematic, never in the realm of mystery.")
    t.append("Here is another example, more immediate, more particular, and which seems to me well fitted to shed light on the difference between problem and mystery:")
    t.append("You make an encounter that turns out to have a profound, indefinite repercussion upon your life. Everyone may have experienced this.")
    t.append("It is obvious that such an encounter poses, if you will, a problem each time; but we also see very clearly that it transcends any problem.")
    t.append("From that moment I find myself in the presence of a mystery, that is to say, of a reality whose roots plunge beyond what can be objectified or inventoried.")

    # SECTION 3: Paras 51-75
    t.append("Only this is very difficult to grasp without distortion. Inevitably I shall be tempted to react against this feeling and to treat the encounter as a mere coincidence.")
    t.append("These clarifications risk, to tell the truth, indirectly strengthening in the minds of my listeners a preliminary objection.")
    t.append("This meta-problematic, it will be said, is nevertheless a content of thought; how then can I fail to ask myself about the mode of its apprehension?")
    t.append("My reply will be here as categorical as possible: to think or more precisely to affirm the meta-problematic is to assert it as that which cannot be reduced to an object of thought.")
    t.append("It must be observed that recollection (recueillement), which has engaged pure philosophers very little, is extremely difficult to define—precisely because it is not an intellectual operation.")
    t.append("Moreover, problematization will operate here as everywhere else, and it is the psychologist who will strive to carry it out.")
    t.append("Within recollection I take up a position—or more precisely I place myself in a condition to take up a position—face to face with my life, in a detachment that is at the same time an interior concentration.")
    t.append("It will be asked: does not recollection merge after all with that dialectical moment of turning back upon oneself, or self-consciousness?")
    t.append("To tell the truth, I do not think so. To enter into oneself does not mean to be for oneself and to admire oneself, so to speak, in the mirror of self-consciousness.")
    t.append("Here again it seems to me that we must be extremely cautious. If it is possible to speak here of an intuition, it is of an intuition that cannot be isolated.")
    t.append("The more central an intuition is, the more it occupies the very depth of the being it illuminates, the less susceptible it is to being isolated as an objective perception.")
    t.append("If we reflect further on what an intuition of being could be, we see that it is not—and cannot be—a spectacle presented to an observer.")
    t.append("We are here at the most difficult point of my entire exposition; instead of using the term intuition, it would be better to speak of an assurance that is at once active and receptive.")
    t.append("I certainly find it regrettable to have to use such abstract language where it is fundamentally a question not of an abstract dialectic, but of a concrete drama.")
    t.append("It is this dramatic aspect that must now be brought to light.")
    t.append("Let us refer back to what I indicated almost at the beginning: the ontological exigence, the exigence of being, can deny itself; it can turn against itself.")
    t.append("If I have placed the emphasis upon despair, upon betrayal, upon suicide, it is because we find in them the most manifest expressions of a will to negation bearing directly upon being.")
    t.append("Let us take despair, for example. We are dealing here with the act by which one despairs of reality as a whole, in the sense in which one despairs of someone. Despair presents itself as the immediate consequence or translation of a balance sheet: so far as I can evaluate the real—and after all, what exceeds my faculties of evaluation is for me as though it were not—I discover in it nothing that resists a process of dissolution which continues in the depth of things and which my reflection enables me to identify and trace. At the root of despair I believe I find this affirmation: there is nothing in reality that allows me to extend credit to it; no guarantee. It is a declaration of absolute insolvency.")
    t.append("Hope, on the other hand, implies precisely this credit. Contrary to what Spinoza asserted, who seems to me to have confused quite distinct notions here, fear is correlative not to hope, but to desire; whereas the negative correlative of hope is the act of putting things at their worst, an act of which what has been called defeatism provides a striking illustration, and which constantly risks degenerating into a desire for the worst. Hope consists in asserting that there is in being, beyond all that is given, beyond all that can provide material for an inventory or serve as the basis for any calculation, a mysterious principle that is in connivance with me, that cannot fail to want what I want, at least if what I want truly deserves to be wanted and is in fact wanted by my whole self.")
    t.append("Yet it is clear that we are here at the center of what I have called the ontological mystery, and the simplest examples are also the best. To hope against all hope that the being I love will triumph over the reputedly incurable disease that undermines him, is to say: it cannot be that I am alone in willing his recovery; it is impossible that reality in its depth should be hostile or merely indifferent to what I affirm to be in itself a good. It is in vain that examples and cases calculated to discourage me are cited: beyond all experience, all probability, all statistics, I affirm that a certain order will be restored, that reality is with me in willing that it should be. I do not merely wish: I affirm; this is what I shall call the prophetic resonance of true hope.")
    t.append("I shall be told: 'In the immense majority of cases, there is nevertheless an illusion here.' But besides the fact that it is of the essence of the act of hope to exclude the consideration of cases, it would be necessary to show here that there exists an ascending dialectic of hope, by which hope is led to transfer itself to a plane that is transcendent in relation to all possible empirical refutations, the plane of salvation as opposed to that of success in whatever form it presents itself.")
    t.append("The fact remains that the correlation of hope and absolute despair persists to the end. They do not seem to me separable. I mean that the structure of the world in which we live permits, and in some way might seem to counsel, an absolute despair; but it is only in such a world that an invincible hope can arise. That is why, moreover, one cannot be too grateful to the great pessimists in the history of thought; they pushed to its limit a certain inner experience that had to be accomplished and whose radical possibility must not be masked by any apologetics; they prepared us to understand that despair could be what it was for Nietzsche: the springboard for the highest affirmation.")
    t.append("On the other hand, it remains certain that, in the very measure in which hope is a mystery, as Péguy saw, this mystery can be misunderstood and converted into a problem. Hope is then treated as a desire that clothes itself in illusory judgments disguising an objective reality whose true character it is in our interest to ignore. What happens here is what we noted regarding encounter or love; it is because the mystery can and in a sense must logically degrade into a problem, that an interpretation such as Spinoza's, with the confusion it implies, must itself be proposed at a given moment. So long as one remains on this side of the ontological, such an attitude cannot be open to criticism. This is very important, and it must be insisted upon. As long as I maintain toward reality the attitude of someone who is not involved in it, but considers himself bound to draw up an exact report (and this is by definition the attitude of the scientist), I am justified in observing toward this reality a kind of distrust on principle that has no theoretical limit of application; such is the attitude of the laboratory worker who cannot in any degree prejudge the results of the analysis he is conducting, and who can all the better contemplate the worst because on that plane the very notion of the worst loses its meaning. But precisely an inquiry of this order, strictly comparable to that undertaken by an auditor of accounts, is pursued on this side of the order of mystery, on this side of the order where the problem encroaches upon its own data.")
    t.append("In reality, when I ask myself, for instance, about the value of life, there is a profound illusion in imagining that I can still maintain this attitude: it is a genuine paralogism to think that I can pursue this inquiry as though I were not myself at stake.")
    t.append("Hence between hope—the reality of hope in the heart of the one whom it inhabits—and the judgments passed upon it by a mind that remains a prisoner of objectivity, there is the very same partition that separates the pure problem from the pure mystery.")

    # SECTION 4: Paras 76-100
    t.append("We stand here at a vital knot of our subject where some particularly intimate connections become visible.")
    t.append("The world of the problematic is at the same time that of desire and fear, which cannot be separated from each other; it is also doubtless the functionalized or functionalizable world that I defined at the beginning of this meditation; it is finally that in which techniques of every kind hold sway. There is no technique that is not directly or cannot be put at the service of some desire, some fear; and conversely every desire or fear will tend to invent the techniques appropriate to it. From this viewpoint despair will consist in recognizing the ultimate inefficacy of techniques, without consenting or managing to place oneself on a terrain where all technique would be recognized as incompatible with the fundamental characters of being, which by its essence escapes our grasp (insofar as our grasp is exercised on the world of objects and on it alone). There lies the reason why it may seem that we have entered today into the very age of despair: we have not ceased to believe in technique—that is to say, to envisage reality as an aggregate of problems—and at the same time, the global bankruptcy of technique is as clearly discernible as are its partial triumphs. To the question: what can man do? we still answer: man can do what his technique can do; but at the same time we must recognize that this technique proves incapable of saving him from himself, and even shows itself capable of concluding the most formidable alliances with the enemy he bears in the depth of his soul.")
    t.append("Surrendered to technique, I said: by that must be understood, increasingly incapable of mastering it or of mastering his own mastery. For this mastery of one's own mastery, which is only the expression on the plane of active life of what I have called reflection to the second power, can find its center or its support only in recollection.")
    t.append("It will be objected that the man most imbued with belief in technique is forced to recognize that there exist immense domains over which in fact his technique has no control. He knows that he cannot prevent death, that he cannot eliminate suffering entirely.")
    t.append("It must be added that the greater the disproportion between the claims of technical intelligence and the tragic reality of human existence, the more violent will be the temptation to despair.")
    t.append("One might say: but after all, this optimism of technical progress was animated by a great hope; how can you separate them?")
    t.append("We must reply, I believe, that metaphysically speaking, the only authentic hope is that which is directed toward what does not depend on ourselves, toward what transcends our technical calculations.")
    t.append("The metaphysical problem of pride, of hubris, which the Greeks perceived and which was one of the essential themes of tragedy, reappears here in all its force. Pride consists precisely in the refusal to recognize this dependence.")
    t.append("This destruction, moreover, can be directed against oneself; pride is by no means incompatible with self-hatred, and it is even there that it achieves its most terrifying form.")
    t.append("A massive and very grave objection is likely to arise at the point we have reached.")
    t.append("Fundamentally, I may be told, is not what you are led to justify ontologically a kind of quietism, an attitude of passivity?")
    t.append("I would observe that this objection implies a series of misunderstandings.")
    t.append("First of all, the idea of an inert hope is in my view contradictory. Hope is not a sort of passive waiting, a sluggish expectation that things will somehow turn out well. It is an active striving.")
    t.append("We have experimental proof of this connection in the fact that it is among the most militant saints that hope has shone with the greatest brilliance.")
    t.append("This word 'creation' presents itself to us here for the first time, yet it is the decisive word. Wherever there is creation, there is victory over the inertia of the problematic.")
    t.append("Great is the temptation to confuse two movements that our spatial metaphors do not permit us to oppose clearly: the movement of turning back upon oneself in self-absorption, and the movement of recollection.")
    t.append("This withdrawal, this recollection, there is good reason to think that aesthetic creation itself presupposes them. Aesthetic creation is impossible without an inward listening.")
    t.append("It may seem that I am approaching here the Bergsonian thesis to the point of coinciding with it. I do not think so, however. Bergson's intuition of duration remains on the threshold of the ontological.")
    t.append("It is important to observe that it seems difficult to save fidelity in a Bergsonian metaphysics, because for Bergson the continuous creation of novelty leaves no room for permanent commitments.")
    t.append("I am inclined to believe that there is in this failure to recognize the values of fidelity something that deeply impairs the notion of duration itself.")
    t.append("Fidelity is in reality the opposite of an inert conformism; it is the active recognition of a certain permanent presence, a presence that demands to be maintained and renewed.")
    t.append("Will it be said that we commonly speak of fidelity to a principle? It remains to be seen whether there is not here an illegitimate transposition of what is properly an interpersonal relation.")
    t.append("Fidelity is so far from being an inert conformism that it implies an active and continuous struggle against the forces that tend to dissolve it, against the erosion of time.")
    t.append("If presence were only an idea in us whose characteristic was to be nothing more than itself, all that we have said about fidelity would collapse into subjective illusion.")
    t.append("If then a creative fidelity is possible, it is because fidelity is ontological in its principle, because it participates in being and bears witness to an unshakeable presence.")

    # SECTION 5: Paras 101-125
    t.append("It is necessary to insist upon this further: a presence to which we remain faithful is not a carefully preserved effigy, a photographic image stored in memory; it is an active, intersubjective communion.")
    t.append("It will be said: what a strange way to define death! Death is a certain phenomenon definable in biological terms; it is the cessation of the vital functions.")
    t.append("We must reply: it is what it means, and what it means for a being placed at the highest spiritual level is not merely an empirical disappearance, but a test of presence.")
    t.append("I shall be told: this is only a translation into unfamiliar and needlessly metaphysical language of a very simple psychological fact, namely that we remember those we love.")
    t.append("I believe that in reality it is a question of something quite different, of an infinitely more mysterious reality. When we say: 'it depends on me that he should still be present to me,' this does not mean that I construct a psychological phantom; it means that I remain open to his spiritual reality.")
    t.append("Here an objection must be anticipated that is the inverse and symmetrical counterpart of the preceding one; I shall be told: granted, you cease to decorate with your metaphysical vocabulary what is only subjective psychology, but do you not then fall into spiritualism?")
    t.append("To answer this objection, I believe it necessary to refer once more to what was said about mystery and recollection. Intersubjective presence is neither an objective physical communication nor an occult transmission; it is an ontological participation.")
    t.append("It must be added—and thereby we prepare to pass into another sphere—that the value of such an intimacy, in which presence is affirmed, depends upon the degree of spiritual availability (disponibilité) that animates it.")
    t.append("The notion of availability is no less important for our subject than that of presence; I would add that between the one and the other there is the closest correlation. To be available is to be capable of being consecrated, of being dedicated.")
    t.append("I would say, to clarify all this, that the available being is the one who is capable of being entirely with me when I am with him, whereas the unavailable being is encumbered with himself.")
    t.append("In reality, at the heart of unavailability we shall always find a certain alienation. One appeals to my sympathy for a misfortune that has befallen someone; I listen, but I am preoccupied with my own affairs, my own anxieties; I am opaque.")
    t.append("Yet the characteristic of the present or available soul is precisely that it does not think in terms of cases: there are no cases for love, there are only persons.")
    t.append("And yet it is clear that the normal growth of an individual involves an increasingly precise and specialized division of his activities, a compartmentalization.")
    t.append("Happily it can happen to each of us to make an encounter that shatters the framework of all this functional topography and restores our openness to being.")
    t.append("Above all, the fact of sanctity realized in certain beings is there to reveal to us that what we call the natural order can be transfigured from within by grace.")
    t.append("To be unavailable is to be in some way not only occupied with oneself, but encumbered with oneself. I say 'in some way': the immediate object can vary indefinitely—to be occupied with oneself, with one's fortune, with one's love affairs, or even with one's inner spiritual progress. One might conclude from this that to be occupied with oneself is much less to be occupied with a certain object—here almost unspecifiable—than to be occupied in a certain manner that remains to be defined. What must be seen is that the contrary of being occupied with oneself is not being empty or indifferent. What is opposed here is rather the opaque being and the transparent being. But this inner opacity itself we must still manage to conceptualize. It is, I think, a kind of blockage or fixation: and I wonder whether, generalizing broadly and interpreting flexibly certain psychoanalytic data, we should not recognize that this fixation, in a given zone or register, is that of a certain anxiety that is not recognized as such. But what is remarkable is that this anxiety persists within the fixation and gives it that clenched, contracted character to which I alluded in connection with degraded will. Everything leads us to think that this indeterminate anxiety is in reality identical with the anguish of temporality, with man's craving not toward, but for death, which lies at the heart of pessimism.")
    t.append("The roots of pessimism are the same as those of unavailability: if the latter increases as we grow older, it is because very often anxiety grows within us to the point of suffocating us; as we approach what we consider an end, this anxiety, in order to protect itself, must bring into play a defensive apparatus that becomes ever heavier, ever more meticulous, and also, I would add, ever more vulnerable. The incapacity for hope is all the more complete as the being becomes more captive to his experience and to the prison of categories with which that experience surrounds him, as he abandons himself more completely, more desperately, to the world of the problematic.")
    t.append("And here the principal motifs or thematic elements that I have had to present successively unite into a single beam. The most available soul is the most consecrated, the most inwardly dedicated: it is protected against despair and against suicide, which resemble each other and join hands, because it knows that it does not belong to itself, and that the only entirely legitimate use it can make of its freedom consists precisely in recognizing that it is not its own master; it is only from this recognition that it can act, that it can create... We must not disguise for a moment the difficulties of every kind that confront a philosophy of this type. It finds itself inevitably placed before a troubling alternative: either it will try to resolve these difficulties, to provide solutions for them, and then it will fall into the excesses of a dogmatism that ignores its principles;")
    t.append("Between these two pitfalls I believe that there exists a via media, a narrow, difficult, perilous path; it is the path that I have tried to trace in this meditation.")
    t.append("Another very grave objection must be mentioned finally. I shall be told: 'In reality, everything you say implies a latent theology; you are doing crypto-theology.'")
    t.append("My reply will be as follows: it is very possible that the existence of fundamental Christian data is required in fact for this philosophy to be conceived and articulated.")
    t.append("On the other hand, if it is said that reason must proceed by abstracting entirely from what is not given to it by its own autonomous light, I would reply that this conception of reason is an abstraction that ignores the concrete conditions of human thought.")
    t.append("I would point out, moreover—and this time it is above all to Catholics that I address myself—that from my point of view the distinction between the natural and the supernatural must be rigorously maintained. Will it be said that the use of the word mystery risks creating an ambiguity here, and favoring a confusion that I reject? I would reply that there is no question in my eyes of confusing the mysteries involved in human experience as such—knowledge, love, for example—with revealed mysteries, such as the Incarnation or the Redemption; to these latter mysteries no effort of thought reflecting upon experience can enable us to elevate ourselves.")
    t.append("It will be said: in these conditions, why use the same word in two such distinct senses? But I would observe here that a revelation, whatever it may be, is after all thinkable only insofar as it addresses an engaged being, in the sense that I have tried to define—that is to say, a being participating in a non-problematizable reality that grounds him as a subject. Supernatural life must find points of contact, points of insertion in natural life—which by no means implies that it is an efflorescence of natural life: quite the contrary. It seems to me that if one deepens the notion fundamental to a Christian of created nature, one is led to recognize in the depth of nature and of a reason ordered to it a principle of radical inadequacy to itself which is like the anxious anticipation of another order.")
    t.append("To summarize my position on this particularly important and difficult point, I would say that the recognition of the ontological mystery, in which I perceive the central stronghold of metaphysics, is doubtless possible in fact only through a kind of fertilizing irradiation of revelation itself, which can perfectly well occur in the hearts of souls that are strangers to any positive religion whatsoever; that this recognition, which takes place through certain higher modalities of human experience, by no means involves adherence to a specific religion, but that it nevertheless enables the one who has risen to it to glimpse the possibility of a revelation in a completely different way from the one who, not having surpassed the bounds of the problematizable, remains on this side of the point where the mystery of being can be perceived and proclaimed. Such a philosophy moves thus with an irresistible momentum to meet a light which it forefeels, and whose secret stimulation and preventing burn it undergoes in the depths of its being.")

    assert len(t) == 125, f"Expected 125, got {len(t)}"
    return t

if __name__ == '__main__':
    generate()

