#!/usr/bin/env python3
"""
Section 5 English translations (Paras 101-125) for Gabriel Marcel's
"Positions et approches concrètes du mystère ontologique"
"""

def get_sec5():
    return [
        # Para 101
        "It is necessary to insist upon this further: a presence to which we remain faithful is not the carefully preserved effigy of a vanished object; an effigy is after all only a simulacrum; metaphysically it is less than the object, it is a reduction of it. Presence on the contrary is more than the object, it overflows it in every direction. We stand here at the entrance of a road at the end of which death appears as a test of presence. An essential point upon which it is fitting to concentrate our attention.",
        
        # Para 102
        "It will be said: what a strange way to define death! It is a certain phenomenon definable in biological terms; it is not a test.",
        
        # Para 103
        "We must reply: it is what it signifies, and what it signifies for a being placed at the highest spiritual level to which it is possible for us to attain. It is obvious that the death of So-and-So, which I learn of through the newspaper, of So-and-So who is for me only a name, is for me merely an object of notification; it means that I must strike So-and-So off the list of people to whom I can apply in order to ask a question or to provide information. It is completely otherwise for a being who has been given to me as a presence. Here it depends on me, on my inward attitude, to maintain this presence which could degrade into an effigy.",
        
        # Para 104
        "I shall be answered: this is only a translation into unfamiliar and needlessly metaphysical language of a very commonplace psychological fact. It is obvious that it depends on us in a certain measure whether the dead live or do not live in our memory. But this is only an entirely subjective existence.",
        
        # Para 105
        "I believe that in reality it is a question of something quite different, of an infinitely more mysterious reality. When one says: 'It depends on us that our dead should live within us,' one still aims at the idea as reduction or as effigy. One admits that the object has vanished, but that a simulacrum survives which it is in our power to maintain in the housekeeping sense of the word, as a housekeeper maintains an apartment, furniture. It is only too clear that such maintenance presents no ontological value whatever. But if fidelity is creative in the sense I have tried to define, it is entirely otherwise. A presence is a reality, a certain influx; it depends on us to remain or not to remain permeable to this influx, though not in truth to generate it. Creative fidelity consists in actively maintaining oneself in a state of permeability; and we see here operating a sort of mysterious exchange between the free act and the gift by which it is answered.",
        
        # Para 106
        "Here an objection must be anticipated that is the inverse and symmetrical counterpart of the preceding one: I shall be told: granted, you cease to decorate with metaphysical terms a commonplace of psychology, but it is in order gratuitously to affirm an unproven thesis that exceeds all possible experience; this is the case from the moment you substitute for the neutral and ambiguous term presence that of influx, which is infinitely more compromising.",
        
        # Para 107
        "To answer this objection, I believe it necessary to refer once more to what was said about mystery and recollection. It is indeed only on meta-problematic ground that the notion of influx can be welcomed here. If it were taken in the objective sense, that of a conveyance of force, we should find ourselves in the presence of a thesis that is not metaphysical at all, but physical, and of a kind to raise effectively every dispute. When I say that a being is given to me as a presence or as being (this comes to the same thing, for he is not a being for me unless he is a presence), that signifies that I cannot treat him as though he were simply placed in front of me; between him and me there is knotted a relation that in a certain sense exceeds the consciousness I am capable of having of it; he is no longer only before me, he is also in me; or more precisely these categories are surpassed, they no longer have meaning. The word influx translates, though in a manner far too spatial, too physical, the kind of interior contribution, of contribution from within that is realized from the moment presence is effective. Great surely, almost invincible will be the temptation to think that this effective presence can only be an objective presence; but thereby we fall back on this side of mystery, to the level of the problematic; and then resounds this protest of absolute fidelity: 'Even when I can neither touch you nor see you, I feel it, you are with me; it would be to deny you not to be assured of it.' With me: let us note here the metaphysical value of this word with, which has been so rarely recognized by philosophers and which corresponds neither to a relation of inherence or immanence, nor to a relation of exteriority. It will be of the essence—I am obliged to adopt here the Latin word—of an authentic coesse, that is to say of a real intimacy, to lend itself to the decomposition which critical reflection makes it undergo; but we already know that there is another reflection, a reflection bearing upon this reflection itself, and which refers to an underlying intuition, blinded but effective, whose secret magnetism it undergoes.",
        
        # Para 108
        "It must be added—and thereby we prepare to pass into another sphere—that the value of such an intimacy, in particular with regard to the communion between the living and the dead, will be all the higher and more irrefutable as this relation is situated more clearly in a world of total spiritual availability (disponibilité), that is to say of pure charity; and I note in passing that an ascending dialectic of creative fidelity corresponds to the dialectic of hope to which I alluded a moment ago.",
        
        # Para 109
        "The notion of availability is no less important for our subject than that of presence; I would add that between the one and the other there exists an evident connection. It is an undeniable fact of experience, though difficult to translate intelligibly, that there are certain beings who reveal themselves to us as present, that is to say here as available when we suffer, when we need to unburden ourselves, and that there are others who do not give us this feeling, whatever their goodwill may be. It must be observed immediately that the distinction between presence and non-presence cannot be reduced in any way to the opposition between being attentive and being distracted. The most attentive, the most conscientious listener can give me the impression of being unavailable; he brings me nothing, he cannot genuinely make room for me in himself, whatever material services he may perhaps shower upon me. In reality there is a way of listening that is a way of giving; there is another way of listening that is a way of refusing, of refusing oneself: the material gift, the visible action is not necessarily a testimony of presence. Let us not speak of proof: here the word proof would clash. Presence is something that reveals itself immediately and irrefutably in a look, a smile, an accent, a grasp of the hands.",
        
        # Para 110
        "I would say, to clarify all this, that the available being is the one who is capable of being entirely with me when I need him; the unavailable being is on the contrary the one who seems to operate in my favor a sort of momentary deduction from the total sum of resources at his disposal. For the first I am a presence; for the second I am an object. Presence envelops a reciprocity that is doubtless excluded by any relation of subject to object or of subject to subject-object. And here a concrete analysis of unavailability is no less necessary than that of betrayal, denial, or despair.",
        
        # Para 111
        "In reality at the heart of unavailability we shall always find a certain alienation. One appeals to my sympathy for a certain misfortune that is explained to me; I understand what is said to me, I recognize in an entirely abstract way that the people being discussed deserve my compassion; I discern there a case to which it would be logical and just to respond with sympathy; this sympathy I grant, if you will, but only in idea; for after all I am forced to confess to myself that I feel nothing. I regret it, moreover; this contradiction between what I experience in fact—that is to say, my indifference—and what I recognize I ought to experience is painful to me and irritates me; it even diminishes me in my own eyes, but all in vain. What remains in me is the rather unavowable feeling that after all they are people I do not know, that if one had to be moved by all human misfortunes life would no longer be possible—that moreover life would not suffice for it. From the moment I think: 'After all, it is only Case 75-627,' it is finished: I can feel nothing more.",
        
        # Para 112
        "Yet the characteristic of the present or available soul is precisely not to think by cases: there are no cases for it.",
        
        # Para 113
        "And yet it is clear that the normal growth of a being implies an increasingly precise and, as it were, automatic apportionment between what concerns him and what does not concern him, what he is responsible for and what he is not responsible for; each of us becomes thus the center of a sort of mental space arranged according to concentric zones of decreasing adherence and interest. It is fundamentally as if each of us secreted an increasingly hard shell that imprisons him; and this sclerosis is bound up with the hardening of the categories according to which we represent the world and evaluate it.",
        
        # Para 114
        "Happily it can happen to each of us to make an encounter that shatters the framework of all this egocentric topography; I can personally understand by experience that from a stranger met by chance there suddenly rises an appeal so irresistible as to overturn all habitual perspectives, exactly as a gust of wind would overturn the staggered planes of a stage set—what seemed close becomes infinitely distant, and conversely; these are breaches that most often close up again almost immediately. These experiences often leave us with a bitter taste, an impression of sadness and almost of anguish: I believe them to be beneficent nonetheless, for they show us as in a flash of lightning how contingent, yes, how accidental are the mental crystallizations that ground our personal system.",
        
        # Para 115
        "Above all, the fact of sanctity realized in certain beings is there to reveal to us that what we call the normal order is after all, from a higher point of view, from the point of view of a soul rooted in the ontological mystery, only the subversion of an opposed order. In this regard, reflection upon sanctity—here again, confrontation with the unavailable soul casts decisive light upon our subject.",
        
        # Para 116
        "To be unavailable is to be in some way not only occupied with oneself, but encumbered with oneself. I say 'in some way': the immediate object can vary indefinitely—to be occupied with oneself, with one's fortune, with one's love affairs, or even with one's inner spiritual progress. One might conclude from this that to be occupied with oneself is much less to be occupied with a certain object—here almost unspecifiable—than to be occupied in a certain manner that remains to be defined. What must be seen is that the contrary of being occupied with oneself is not being empty or indifferent. What is opposed here is rather the opaque being and the transparent being. But this inner opacity itself we must still manage to conceptualize. It is, I think, a kind of blockage or fixation: and I wonder whether, generalizing broadly and interpreting flexibly certain psychoanalytic data, we should not recognize that this fixation, in a given zone or register, is that of a certain anxiety that is not recognized as such. But what is remarkable is that this anxiety persists within the fixation and gives it that clenched, contracted character to which I alluded in connection with degraded will. Everything leads us to think that this indeterminate anxiety is in reality identical with the anguish of temporality, with man's craving not toward, but for death, which lies at the heart of pessimism.",
        
        # Para 117
        "The roots of pessimism are the same as those of unavailability: if the latter increases as we grow older, it is because very often anxiety grows within us to the point of suffocating us; as we approach what we consider an end, this anxiety, in order to protect itself, must bring into play a defensive apparatus that becomes ever heavier, ever more meticulous, and also, I would add, ever more vulnerable. The incapacity for hope is all the more complete as the being becomes more captive to his experience and to the prison of categories with which that experience surrounds him, as he abandons himself more completely, more desperately, to the world of the problematic.",
        
        # Para 118
        "And here the principal motifs or thematic elements that I have had to present successively unite into a single beam. The most available soul is the most consecrated, the most inwardly dedicated: it is protected against despair and against suicide, which resemble each other and join hands, because it knows that it does not belong to itself, and that the only entirely legitimate use it can make of its freedom consists precisely in recognizing that it is not its own master; it is only from this recognition that it can act, that it can create... We must not disguise for a moment the difficulties of every kind that confront a philosophy of this type. It finds itself inevitably placed before a troubling alternative: either it will try to resolve these difficulties, to provide solutions for them, and then it will fall into the excesses of a dogmatism that ignores its vital principles, and, I would add, of a sacrilegious theodicy; or else it will simply leave these difficulties to subsist by labeling them as mysteries.",
        
        # Para 119
        "Between these two pitfalls I believe that there exists a via media, a narrow, difficult, perilous path; it is the path that I have striven not to trace, but to identify. Only one can proceed here only by appeals, like Karl Jaspers in his Philosophy of Existence: if, as I have had occasion to observe, certain minds respond—not consciousness in general, but this being, that other being—it is because there truly is a path. But—as Plato, I think, saw with incomparable clarity—this path can be discovered only by love, it is visible to love alone: and here appears a characteristic deeper perhaps than all the others of this meta-problematic whose regions I have attempted to explore.",
        
        # Para 120
        "Another very grave objection must be mentioned finally. I shall be told: 'In reality, everything you say implies a reference—unavowed, unformulated, moreover—to Christian data, and is positively illuminated only by their light. It is thus that we understand what you mean by presence when we evoke the Eucharist, or by creative fidelity when we think of the Church. But then what will be the value of such a philosophy for non-Christian minds, that is to say, those who are ignorant of Christianity or in any case declare themselves incapable of adhering to it?'",
        
        # Para 121
        "My reply will be as follows: it is very possible that the existence of fundamental Christian data is required in fact to permit the mind to conceive some of the notions of which I have sketched the analysis: but one surely cannot say that these notions are in dependence upon Christian revelation; they do not presuppose it.",
        
        # Para 122
        "On the other hand, if it is said that reason must proceed by abstracting entirely from what is not given universally to a thinking being of whatever kind, I would say that there is here an abusive claim and in the last analysis an illusion. The philosopher today, as in every epoch, finds himself placed in a certain historical situation from which it is very little likely that he is in a position genuinely to abstract himself: it is only by a fiction of which he is the dupe that he imagines he can make a void in himself and around himself. Now, this situation implies as one of its essential data the existence of the Christian fact with all that it implies—whether one adheres or not to the Christian religion, whether one considers the central Christian affirmations as true or false. What is clear in my eyes is that we cannot think as if there had not been before us centuries of Christianity, just as, in the order of the theory of knowledge, we cannot think as if there had not been centuries of positive science. Only, the existence of the Christian given, like that of positive science, plays here only the role of a fertilizing principle. It fosters in us the blooming of certain thoughts to which in fact we might perhaps not have had access without it. This fertilization can be accomplished in what I shall call peri-Christian zones, and I personally find proof of this in the fact that it occurred in myself nearly twenty years before I had even the most distant idea of converting to Catholicism.",
        
        # Para 123
        "I would point out, moreover—and this time it is above all to Catholics that I address myself—that from my point of view the distinction between the natural and the supernatural must be rigorously maintained. Will it be said that the use of the word mystery risks creating an ambiguity here, and favoring a confusion that I reject? I would reply that there is no question in my eyes of confusing the mysteries involved in human experience as such—knowledge, love, for example—with revealed mysteries, such as the Incarnation or the Redemption; to these latter mysteries no effort of thought reflecting upon experience can enable us to elevate ourselves.",
        
        # Para 124
        "It will be said: in these conditions, why use the same word in two such distinct senses? But I would observe here that a revelation, whatever it may be, is after all thinkable only insofar as it addresses an engaged being, in the sense that I have tried to define—that is to say, a being participating in a non-problematizable reality that grounds him as a subject. Supernatural life must nonetheless find in natural life points of hold, points of insertion—which by no means implies that it is an efflorescence of natural life: quite the contrary. It seems to me that if one deepens the notion fundamental to a Christian of created nature, one is led to recognize in the depth of nature and of a reason ordered to it a principle of radical inadequacy to itself which is like the anxious anticipation of another order.",
        
        # Para 125
        "To summarize my position on this particularly important and difficult point, I would say that the recognition of the ontological mystery, in which I perceive the central stronghold of metaphysics, is doubtless possible in fact only through a kind of fertilizing irradiation of revelation itself, which can perfectly well occur in the hearts of souls that are strangers to any positive religion whatsoever; that this recognition, which takes place through certain higher modalities of human experience, by no means involves adherence to a specific religion, but that it nevertheless enables the one who has risen to it to glimpse the possibility of a revelation in a completely different way from the one who, not having surpassed the bounds of the problematizable, remains on this side of the point where the mystery of being can be perceived and proclaimed. Such a philosophy moves thus with an irresistible momentum to meet a light which it forefeels, and whose secret stimulation and preventing burn it undergoes in the depths of its being."
    ]

